---
title: "Report_scRNA"
author: "Lauren Liao"
date: "11/3/2020"
output: html_document
---

```{r include=FALSE}
source("combine_analyze_multiple_samples_updated.R")
```

The tSNE plot with 12 clusters in total.
```{r}
plot5
```

#### after looking at the link
##### left being the mouse database and right being the human database seperated by semicolon (if I didn't make a mistake)
* 0: MO = Macro; LEUK  
* 1, 2: PT(S3); PT
* 4: Endo; Endo
* 3: LH(DL); diverse
* 5: IC-A; ICB or ICA
* 6: diverse; LEUK
* 7: diverse; seems to be PT or LEUK
* 8: LH(AL); TAL
* 9: CD-PC; PC
* 10: MC; Fib or Mes
* 11: Neutro; LEUK

```{r}
as.data.frame(marker_genes_cluster)
```

some codes that you may be of interest to modify
```{r eval=FALSE}

kidney <- FindVariableFeatures(object = kidney, selection.method = "vst", nfeatures = 1050)

kidney <- ScaleData(object = kidney, vars.to.regress = c("nCount_RNA", "percent.mt"))

kidney <- RunPCA(object = kidney, pc.genes = kidney@assays[["RNA"]]@var.features, do.print = TRUE, pcs.print = 1:5, genes.print = 5)

kidney <- FindNeighbors(kidney, reduction = "pca", dims = 1:10)

kidney <- FindClusters(kidney, resolution = 0.2, verbose = 0, save.SNN = TRUE)

kidney <- RunTSNE(object = kidney, dims.use = 1:10, do.fast = TRUE, do.label= TRUE)

all.markers = FindAllMarkers(kidney,
                             min.pct = MIN_PCT_CELLS_EXPR_GENE,
                             logfc.threshold = MIN_LOGFOLD_CHANGE,
                             only.pos = TRUE)

marker_genes_cluster <- all.markers %>% group_by(cluster) %>% top_n(20, avg_logFC)
```